@BookStore.Api_HostAddress = http://localhost:5160

###
GET http://localhost:5160/api/books

###
GET  http://localhost:5160/api/books/5

###
POST http://localhost:5160/api/books
Content-Type: application/json

{
    "title": "ffhd",
    "author":"Ham",
    "price": 1,
    "stockQty": 0
}

###
PUT http://localhost:5160/api/books/1
Content-Type: application/json

{
    "title": "Ha",
    "author": "yes",
    "price": "15.50",
    "stockQty": "5"
}

### 
DELETE http://localhost:5160/api/books/4

